# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: true
  ap:
    ssid: "${name} Fallback AP"
    password: !secret wifi_ap_password

web_server:
  port: 80

captive_portal:

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP address"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"

sensor:
  - platform: uptime
    name: "Uptime"
    device_class: duration

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

switch:
  - platform: restart
    name: "Restart"

