esphome:
  name: connor_lights
  platform: ESP8266
  board: esp01
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
logger:
api:
sensor:
  - platform: wifi_signal
    name: "Connor Lights WiFi Signal"
    update_interval: 60s
#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w
light:
  - platform: rgb
    name: "Connor Lights"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    effects:
      - random:
      - random:
          name: "Slow Random"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random"
          transition_length: 4s
          update_interval: 5s

