esphome:
  name: connor-lights
  friendly_name: Connor Lights

packages:
  common: !include include/common.yaml
  h801: !include devices/h801.yaml

# This happens to be a low-flash variant, only 512kB
esp8266:
  board: esp01

# remove components to fit into flash
ota: !remove
time: !remove
web_server: !remove
captive_portal: !remove

light:
  - id: !extend rgbw_
    name: "Connor Lights"
    effects:
      - random:
      - random:
          name: "Slow Random"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random"
          transition_length: 4s
          update_interval: 5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
