esphome:
  name: "courtyard-garden-lights"
  friendly_name: "Courtyard and Garden Lights"

packages:
  common: !include include/common.yaml
  device: !include include/sonoff_dual_r3.yaml

light:
   - id: !extend sw1
     restore_mode: ALWAYS_ON
   - id: !extend sw2
     restore_mode: ALWAYS_ON
