esphome:
  name: "courtyard-light"
  friendly_name: "Courtyard Light"
  on_boot: 
    priority: 500
    then:
      - light.turn_on: light_1

packages:
  common: !include .common.yaml
  device: !include include/sonoff_basic_light.yaml

light:
   - id: !extend light_1
     restore_mode: ALWAYS_ON
