esphome:
  name: currentcost
  friendly_name: CurrentCost
  platformio_options:
    upload_speed: 460800
    build_flags: -DRAPIDXML_STATIC_POOL_SIZE=1024 -DRAPIDXML_DYNAMIC_POOL_SIZE=1024
    build_unflags: -fno-exceptions
  includes:
     - rapidxml
     - currentcost.h

packages:
  common: !include include/common.yaml

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  baud_rate: 0
#  level: VERBOSE

bluetooth_proxy:

#esp32_ble_tracker:

sensor:
  - platform: custom
    lambda: |-
      auto currentcost = new CurrentCostSensor(id(uart_bus));
      App.register_component(currentcost);
      return {currentcost->ch1, currentcost->ch2, currentcost->ch3};
    sensors:
      - id: "ch1"
        name: "currentcost_ch1"
        unit_of_measurement: W
        accuracy_decimals: 0
      - id: "ch2"
        name: "currentcost_ch2"
        unit_of_measurement: W
        accuracy_decimals: 0
      - id: "ch3"
        name: "currentcost_ch3"
        unit_of_measurement: W
        accuracy_decimals: 0

uart:
  id: uart_bus
  rx_pin: GPIO18
  tx_pin: GPIO19
  baud_rate: 57600
  rx_buffer_size: 1024
  debug:
    direction: RX
