esphome:
  name: "cycad-light"
  friendly_name: "Cycad Light"

packages:
  common: !include include/common.yaml
  device: !include devices/sonoff_basic_light.yaml

light:
   - id: !extend light_1
     restore_mode: ALWAYS_ON
