esphome:
  name: dishwasher
  friendly_name: Dishwasher

bk72xx:
  board: generic-bk7231t-qfn32-tuya

#libretiny:
#  board: generic-bk7231t-qfn32-tuya
#  framework:
#    version: dev

logger:

web_server:

captive_portal:

mdns:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

button:
- platform: restart
  name: Restart

debug:
  update_interval: 30s

text_sensor:
- platform: debug
  reset_reason:
    name: Reset Reason
- platform: libretiny
  version:
    name: LibreTiny Version

sensor:
- platform: uptime
  name: Uptime

- platform: hlw8012
  model: BL0937
  cf_pin:
    number: P7
    inverted: true
  cf1_pin:
    number: P8
    inverted: true
  sel_pin:
    number: P24
    inverted: true
  current:
    name: Current
  power:
    name: Power
    id: power
  energy:
    name: Energy
  voltage_divider: 800
  current_resistor: 0.001 ohm
  initial_mode: CURRENT
  change_mode_every: 4294967295
  update_interval: 30s

binary_sensor:
- platform: gpio
  id: binary_switch_1
  pin:
    number: P10
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: switch_1

- platform: template
  name: "Running"
  filters:
    - delayed_on_off: 120s
  lambda: |-
    if (isnan(id(power).state)) {
      return {};
    } else if (id(power).state > 4) {
      // Running
      return true;
    } else {
      // Not running
      return false;
    }

switch:
- platform: gpio
  id: switch_1
  name: Relay 1
  pin: P26
  restore_mode: ALWAYS_ON

status_led:
  pin: P6

