esphome:
  name: dishwasher
  friendly_name: Dishwasher

packages:
  common: !include include/common.yaml
  connex: !include include/connex-plug.yaml

binary_sensor:
  - platform: template
    name: "Running"
    filters:
      - delayed_on_off: 60s
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }

switch:
  - id: !extend sw1
    restore_mode: ALWAYS_ON

