substitutions:
  devicename: driveway-light
  upper_devicename: Driveway Light

esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home.dawes.za.net

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
    # key: "P6IoNk0dZLhK28EutCtu+d5nNRDlbEjghNgnQIHlBZY="

# Enable logging
logger:

ota:
  platform: esphome
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    internal: true
    on_press:
      - light.toggle: relay

text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: BSSID

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: Restart

output:
  - platform: gpio
    pin: GPIO12
    id: relay_output

light:
  - platform: binary
    id: relay
    name: "${upper_devicename}"
    output: relay_output
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes
