esphome:
  name: garage-light
  friendly_name: Garage Light
  on_boot: 
    priority: 500
    then:
      - light.turn_on: garage_light

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home.dawes.za.net

logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MC0VLbVdJr76rSPPt+fBoOJZyS0HxTAytnXD2S5fQAQ="

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: Garage Light ESPHome Version
  - platform: wifi_info
    ip_address:
      name: Garage Light IP
    ssid:
      name: Garage Light SSID
    bssid:
      name: Garage Light BSSID

sensor:
  - platform: uptime
    name: Garage Light uptime
  - platform: wifi_signal
    name: "Garage Light WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Garage Light Button"
    on_press:
      - light.toggle: garage_light

output:
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: binary
    id: garage_light
    name: "Garage light"
    output: relay

switch:
  - platform: restart
    name: Garage Light Restart

status_led:
  pin:
    number: GPIO13
    inverted: yes
