esphome:
  name: garage-lights
  friendly_name: Garage Lights

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "317Fp2utUwxOjiga5OnXwuyeVunAoMaC9cCMgMEVuLY="

ota:
  platform: esphome
  password: !secret ota_password
#  password: "42469f8f7c7e6fdb07101526a0b545bc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home.dawes.za.net

text_sensor:
  - platform: version
    name: Garage Lights ESPHome Version
  - platform: wifi_info
    ip_address:
      name: Garage Lights IP
    ssid:
      name: Garage Lights SSID
    bssid:
      name: Garage Lights BSSID

sensor:
  - platform: uptime
    name: Garage Lights uptime
  - platform: wifi_signal
    name: "Garage Lights WiFi Signal"
    update_interval: 60s

switch:
  - platform: restart
    name: Garage Lights Restart

#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w

light:
  - platform: rgbw
    name: "Garage Lights"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    effects:
      - random:
      - random:
          name: "Slow Random"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random"
          transition_length: 4s
          update_interval: 5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
