esphome:
  name: garage-lights
  friendly_name: Garage Lights

esp8266:
  board: esp01_1m

packages:
  common: !include include/common.yaml
  h801: !include include/h801.yaml

light:
  - id: !extend rgbw_
    name: "Garage Lights"
    effects:
      - random:
      - random:
          name: "Slow Random"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random"
          transition_length: 4s
          update_interval: 5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
