esphome:
  name: "mozzi"
  friendly_name: "Mozzi"

packages:
  common: !include .common.yaml
  device: !include include/sonoff_dual_r3.yaml

light:
   - id: !extend sw1
     restore_mode: ALWAYS_ON
   - id: !extend sw2
     restore_mode: ALWAYS_ON
