esphome:
  name: patio-dimmer
  on_boot:
    - light.turn_on: 
        id: dimmer

bk72xx:
  board: wb2s

#libretuya:
#  board: wb2s
#  framework:
#    version: dev

# Enable logging
logger:
  level: info
  logs:
    scheduler: NONE

# Enable Home Assistant API
api:
  password: ""

ota:
  platform: esphome
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Patio-Dimmer Fallback Hotspot"
    password: "0seZtoyBs3lm"
    
uart:
  - id: uart_tuya
    rx_pin: RX1
    tx_pin: TX1

    baud_rate: 115200

tuya:
  on_datapoint_update:
    - sensor_datapoint: 20
      datapoint_type: bool
      then:
        - if:
            condition:
              and:
                - light.is_on: dimmer
                - lambda: 'return !x;'
#                lambda: 'return esphome::millis() < 60000 && !x;'
            then:
              - logger.log: "Turning the light back on"
              - delay: 10ms
              - light.turn_on: 
                  id: dimmer

light:
  - platform: "tuya"
    id: dimmer
    name: "Patio dimmer"
    dimmer_datapoint: 22
    min_value_datapoint: 26
    switch_datapoint: 20
    min_value: 50
    max_value: 1000

switch:
  - platform: restart
    name: "Patio Dimmer Restart"
