esphome:
  name: patio-dimmer
  friendly_name: Patio Dimmer
  on_boot:
    - light.turn_on: 
        id: dimmer

packages:
  common: !include include/common.yaml
  dimmer: !include devices/tuya_dimmer.yaml
