esphome:
  name: pool
  friendly_name: Pool

packages:
  common: !include include/common.yaml
  sonoff: !include devices/sonoff_4ch_pro.yaml

sensor:
  - platform: pulse_counter
    pin: 
      number: GPIO2
      mode: INPUT
    id: flow_rate
    name: "flow rate"

binary_sensor:
  - id: !remove button_3
  - id: !extend button_4
    on_press:
      - then:
          light.toggle: pool_light

switch:
  - id: !extend relay_1
    name: "Pump"
  - id: !extend relay_2
    name: "Water feature"
  - id: !remove relay_3
  - id: !remove relay_4

light:
  - platform: binary
    name: "Light"
    id: pool_light
    output: output_4

