esphome:
  name: s3-matrix
  friendly_name: s3-matrix

# Replace this with your actual platform if you aren't using ESP32.
esp32:
  variant: ESP32S3

logger:

api:
  encryption:
    key: "9MAKzQO87EyrBlGsBG9lj4xoF8B1mFUgxbVsq+3s4x4="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: s3-matrix Fallback Hotspot
    password: "bQAOdgyexMju"

captive_portal:

light:
  - platform: esp32_rmt_led_strip
    name: matrix
    pin: GPIO14
    id: light_esp32_rmt_led_strip_1
    chipset: WS2812
    num_leds: 64
    rgb_order: RGB

i2c:
  - scl: GPIO12
    sda: GPIO11
    id: i2c_1

motion:
  - platform: qmi8658
    accelerometer_range: 4G
    gyroscope_range: 2048DPS

sensor:
  - platform: motion
    type: acceleration_x
    name: "QMI8658 Accel X"
  - platform: motion
    type: gyroscope_x
    name: "QMI8658 Gyro X"
  - platform: motion
    type: roll
    name: "QMI8658 Roll"

  - platform: qmi8658
    type: temperature # Optional, temperature is the only supported type for this platform
    name: "QMI8658 Temperature"