substitutions:
  devicename: sonoff-s26
  upper_devicename: Sonoff S26

esphome:
  name: sonoff-s26
  friendly_name: Sonoff S26

packages:
  common: !include include/common.yaml
  sonoff: !include devices/sonoff_basic.yaml

switch:
  - id: !extend relay_1
    restore_mode: ALWAYS_ON
