esphome:
  name: sunsynk
  comment: 'SunSynk'
  
esp32:
  board: airm2m_core_esp32c3
  framework:
    type: arduino
  variant: esp32c3

packages:
  common: !include include/common.yaml
  modbus: !include include/sunsynk_modbus.yaml

# Disable logging
logger:
  baud_rate: 0

uart:
  - id: mod_bus
    tx_pin: GPIO5
    rx_pin: GPIO6
    baud_rate: 9600
 
modbus:
  id: inverter_modbus
 
modbus_controller:
  - id: inverter
    address: 0x01
    modbus_id: inverter_modbus
    setup_priority: -10
    update_interval: "15s"
    command_throttle: "50ms"

