esphome:
  name: sunsynk
  comment: 'SunSynk'
  
packages:
  device: !include devices/sunsynk_dongle.yaml
  common: !include include/common.yaml
  modbus: !include
    file: include/sunsynk_modbus.yaml
    vars:
      modbus_controller_id: inverter
      id_prefix: inverter_
      # If you set a name prefix, also include a trailing space character
      name_prefix: "Inverter "

# Disable UART logging
logger:
  baud_rate: 0

bluetooth_proxy:
  active: true

esp32_ble_tracker:

modbus:
  id: inverter_modbus
  uart_id: mod_bus
 
modbus_controller:
  - id: inverter
    address: 0x01
    modbus_id: inverter_modbus
    setup_priority: -10
    update_interval: "15s"
    command_throttle: "50ms"

