esphome:
  name: washing-machine
  friendly_name: Washing Machine

packages:
  common: !include include/common.yaml
  connex: !include include/connex-plug.yaml

switch:
  - id: !extend sw1
    restore_mode: ALWAYS_ON

