esphome:
  name: washing-machine
  friendly_name: Washing Machine

bk72xx:
  board: generic-bk7231t-qfn32-tuya

#libretiny:
#  board: generic-bk7231t-qfn32-tuya
#  framework:
#    version: dev

logger:

web_server:

captive_portal:

mdns:

api:
  encryption: 
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: 192.168.201.146
  ap:

button:
- platform: restart
  name: Restart

debug:
  update_interval: 30s

text_sensor:
- platform: debug
  reset_reason:
    name: Reset Reason
- platform: libretiny
  version:
    name: LibreTiny Version

sensor:
- platform: uptime
  name: Uptime

- platform: hlw8012
  model: BL0937
  cf_pin:
    number: P7
    inverted: true
  cf1_pin:
    number: P8
    inverted: true
  sel_pin:
    number: P24
    inverted: true
  current:
    name: Current
  power:
    name: Power
    id: power
  energy:
    name: Energy
  voltage_divider: 800
  current_resistor: 0.001 ohm
  initial_mode: CURRENT
  change_mode_every: 4294967295
  update_interval: 30s

binary_sensor:
- platform: gpio
  id: binary_switch_1
  pin:
    number: P10
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: switch_1

switch:
- platform: gpio
  id: relay
  pin: P26
  restore_mode: ALWAYS_ON

- platform: template
  id: switch_1
  name: Relay 1
  lambda: |-
    return id(relay).state;
  turn_on_action:
    - switch.turn_on: relay
  turn_off_action:
    if:
      condition:
        lambda: 'return id(power).get_state() > 2.8;'
      then:
        - switch.template.publish:
            id: switch_1
            state: ON
      else:
        - switch.turn_off: relay


status_led:
  pin: P6

