esp8266:
  board: esp8285

i2c:
  scan: true
  id: i2c_a

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

font:
  - file: "gfonts://fonts/fontawesome-webfont.ttf"
    id: my_font
    size: 20

display:
  - platform: st7735
    model: "INITR_GREENTAB"
#    reset_pin: D4
    cs_pin: GPIO15
    dc_pin: GPIO2
    rotation: 270
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 1s
    id: my_display

sensor:
  - platform: adc
    pin: A0
    name: "Buttons"
    update_interval: 100ms
    internal: true
    on_value_range:
      - above: 0.99
        then:
          - binary_sensor.template.publish:
              id: button_up
              state: OFF
          - binary_sensor.template.publish:
              id: button_down
              state: OFF
          - binary_sensor.template.publish:
              id: button_power
              state: OFF
          - binary_sensor.template.publish:
              id: button_settings
              state: OFF
      - above: 0.75
        below: 0.80
        then:
          - binary_sensor.template.publish:
              id: button_up
              state: OFF
          - binary_sensor.template.publish:
              id: button_down
              state: ON
          - binary_sensor.template.publish:
              id: button_power
              state: OFF
          - binary_sensor.template.publish:
              id: button_settings
              state: OFF
      - above: 0.41
        below: 0.44
        then:
          - binary_sensor.template.publish:
              id: button_up
              state: OFF
          - binary_sensor.template.publish:
              id: button_down
              state: OFF
          - binary_sensor.template.publish:
              id: button_power
              state: OFF
          - binary_sensor.template.publish:
              id: button_settings
              state: ON
      - above: 0.36
        below: 0.38
        then:
          - binary_sensor.template.publish:
              id: button_up
              state: OFF
          - binary_sensor.template.publish:
              id: button_down
              state: ON
          - binary_sensor.template.publish:
              id: button_power
              state: OFF
          - binary_sensor.template.publish:
              id: button_settings
              state: ON
      - above: 0.29
        below: 0.30
        then:
          - binary_sensor.template.publish:
              id: button_up
              state: ON
          - binary_sensor.template.publish:
              id: button_down
              state: OFF
          - binary_sensor.template.publish:
              id: button_power
              state: OFF
          - binary_sensor.template.publish:
              id: button_settings
              state: OFF
      - above: 0.26
        below: 0.27
        then:
          - binary_sensor.template.publish:
              id: button_up
              state: ON
          - binary_sensor.template.publish:
              id: button_down
              state: ON
          - binary_sensor.template.publish:
              id: button_power
              state: OFF
          - binary_sensor.template.publish:
              id: button_settings
              state: OFF
      - above: 0.20
        below: 0.22
        then:
          - binary_sensor.template.publish:
              id: button_up
              state: ON
          - binary_sensor.template.publish:
              id: button_down
              state: OFF
          - binary_sensor.template.publish:
              id: button_power
              state: OFF
          - binary_sensor.template.publish:
              id: button_settings
              state: ON
      - above: 0.00
        below: 0.10
        then:
          - binary_sensor.template.publish:
              id: button_up
              state: OFF
          - binary_sensor.template.publish:
              id: button_down
              state: OFF
          - binary_sensor.template.publish:
              id: button_power
              state: ON
          - binary_sensor.template.publish:
              id: button_settings
              state: OFF

  - platform: htu21d
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 30s

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO12
      mode:
        input: true
        pullup: true
    id: pir

  - platform: template
    id: button_up

  - platform: template
    id: button_down

  - platform: template
    id: button_power

  - platform: template
    id: button_settings

output:
  - platform: esp8266_pwm
    pin: GPIO16
    id: rtttl_out

rtttl:
  output: rtttl_out

