packages:
  device: !include motor_supervisor_v1.yaml

binary_sensor:
    # We don't need the binary sensors, we only use PWM/duty cycle
  - id: !remove motor_a
  - id: !remove motor_b

  # Movement sensors trigger when one motor is at 100%, and the other has dropped to below 80% after initial acceleration
  - platform: template
    id: open_movement
    condition:
      and:
        - sensor.in_range:
            id: motor_a_duty_cycle
            above: 20.0
            below: 81.0
        - sensor.in_range:
            id: motor_b_duty_cycle
            above: 99.0
    filters:
      - delayed_on: 100ms # Don't trigger during the acceleration ramp up to 100%
      - delayed_off: 2s   # Remain on during the deceleration ramp, to turn the endstop on

  - platform: template
    id: close_movement
    condition:
      and:
        - sensor.in_range:
            id: motor_a_duty_cycle
            above: 99.0
        - sensor.in_range:
            id: motor_b_duty_cycle
            above: 20.0
            below: 81.0
    filters:
      - delayed_on: 100ms # Don't trigger during the acceleration ramp up to 100%
      - delayed_off: 2s   # Remain on during the deceleration ramp, to turn the endstop on

  # The endstop sensors depend on the currently detected movement, and the deceleration spike to above 80%
  - platform: template
    id: open_endstop
    condition:
      - and:
        - binary_sensor.is_on: open_movement
        - sensor.in_range:
            id: motor_a_duty_cycle
            above: 80.0
    filters:
      - delayed_off: 3s

  - platform: template
    id: close_endstop
    condition:
      and:
        - binary_sensor.is_on: close_movement
        - sensor.in_range:
            id: motor_b_duty_cycle
            above: 80.0
    filters:
      - delayed_off: 3s

sensor:
  # By observation of the duty_cycle values for motor_a and motor_b, it can be observed that
  # both values spike from 0 to 100% when the motor starts moving in either direction, but then
  # one value drops to around 45-55% after about 1.2s. If the cover is stopped externally, the
  # PWM values drop immediately to zero. However, if the controller detects that it is approaching
  # its limits, the duty cycle then rises to either 100% (opening endstop) or around 95% (closing endstop).
  # This allows us to detect when the controller believes the cover is completely open or closed.
  # The filters were added after the fact to reduce log verbosity and simplify comparisons.

  - id: !extend motor_a_duty_cycle
    filters:
      - round_to_multiple_of: 5
      - delta: 1

  - id: !extend motor_b_duty_cycle
    filters:
      - round_to_multiple_of: 5
      - delta: 1

button:
  - platform: output
    output: out_1
    id: trg
    duration: 200ms

# The cover exposed to Home Assistant, representing the door's motion
# Note that the open_action, close_action, stop_action are not guaranteed
# to perform the expected action, it all depends on what the cover was
# doing previously. I tried a scripted approach to this, but it failed
# miserably. Feels like it needs to be integrated into the cover somehow
# since there is already a "cover.toggle()" method, it clearly knows its
# own state, even if it is not exposed. Exposing it is probably the first
# step.
cover:
  - platform: feedback
    id: cover_
    name: None
    device_class: garage
    has_built_in_endstop: true
    infer_endstop_from_movement: false
    direction_change_wait_time: 2s
    acceleration_wait_time: 2s

    open_action:
      - button.press: trg
    open_duration: 14s
    open_sensor: open_movement
    open_endstop: open_endstop

    close_action:
      - button.press: trg
    close_duration: 16s
    close_sensor: close_movement
    close_endstop: close_endstop

    stop_action:
      - button.press: trg

