sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    address: ${volt_address}
    register_type: read
    name: "${battery} CellVoltage${cell}"
    id: ${modbus_controller_id}_${cell}_volt
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 3
    entity_category: diagnostic
    filters:
    - multiply: 0.001
    skip_updates: 5

