sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    address: ${temp_address}
    register_type: read
    name: "${battery} TempCell${cell}"
    id: ${modbus_controller_id}_${cell}_temp
    unit_of_measurement: C
    device_class: temperature
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    entity_category: diagnostic
    filters:
    - offset: -400
    - multiply: 0.1
    skip_updates: 5

