esp32:
  variant: esp32s3
  framework:
    type: esp-idf

binary_sensor:
  - platform: gpio
    id: user_button
    pin:
      number: GPIO21
      inverted: true

output:
  - platform: ledc
    id: user_led_output
    pin: GPIO48

spi:
  - id: lora_spi
    clk_pin: GPIO7
    miso_pin: GPIO8
    mosi_pin: GPIO9

### SX1262 on Wio shield
sx126x:
  id: sx126x_id
  busy_pin: GPIO40
  cs_pin: GPIO41
  dio1_pin: GPIO39
  rst_pin: GPIO42
  hw_version: sx1262
  rf_switch:  true
  tcxo_voltage: 3_0V
  tcxo_delay: 5ms

