packages:
  basic: !include sonoff_basic.yaml

switch:
  - id: !remove relay_1

binary_sensor:
  - id: !extend button_1
    on_press: !remove
  - id: !extend button_1
    on_press:
      then:
        - light.toggle: light_1

light:
  - platform: binary
    name: "switch"
    id: light_1
    output: output_1

