esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - switch.toggle: relay_1

output:
  - platform: gpio
    pin: GPIO12
    id: output_1

status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
  - platform: output
    name: "switch"
    id: relay_1
    output: output_1

