esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

binary_sensor:
  # single button that also puts device into flash mode when held on boot
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
      ignore_strapping_warning: true
    id: button_
    filters:
      - delayed_on_off: 50ms

switch:
  - platform: hbridge
    id: main_relay
    on_pin:
      number: GPIO19
      inverted: true
    off_pin:
      number: GPIO22
      inverted: true
    pulse_length: 100ms
    wait_time: 100ms

output:
  - platform: ledc 
    id: red_led_output
    pin:
      number: GPIO16
      inverted: true

  - platform: ledc 
    id: green_led_output
    pin:
      number: GPIO13
      inverted: true

  # This is needed to power the external sensor.
  # It receives 3v3 from this pin, which is pulled up on boot.
  - platform: gpio
    pin: GPIO27
    id: sensor_power
    
button:
# The middle (blue) LED is used as wifi status indicator.
status_led:
  pin:
    number: GPIO15
    inverted: true
    ignore_strapping_warning: true

light:
  # Leftmost (red) LED that's used to indicate the relay being on/off
  - platform: binary
    id: red_led
    output: red_led_output
    internal: true

  # Rightmost (green) LED
  - platform: binary
    id: green_led
    output: green_led_output
    internal: true

one_wire:
  platform: gpio
  pin: GPIO25

