# Substitutions allow easy generation of firmware binaries
# that contain no private information, or have a different
# logger level set
#
# e.g.:
# $ esphome -s public true -s logger_level DEBUG run example.yaml

substitutions:
  private_overrides: !include private.yaml
  public: false
  logger_level: INFO

# Enable logging
logger:
  level: ${logger_level}

# Enable Home Assistant API
api:

ota:
  platform: esphome

time:
  platform: sntp

wifi:
  ap:

web_server:
  port: 80

captive_portal:

text_sensor:
  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "IP address"
      entity_category: diagnostic
    ssid:
      name: "SSID"
      entity_category: diagnostic
    bssid:
      name: "BSSID"
      entity_category: diagnostic

sensor:
  - platform: uptime
    name: "Uptime"
    device_class: duration
    disabled_by_default: true
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    disabled_by_default: true
    entity_category: diagnostic

button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: safe_mode
    name: "Reboot to Safe Mode"
    entity_category: config

packages:
  - ${ {} if public else private_overrides }
