text_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    register_type: read
    address: 0
    raw_encode: HEXBYTES
    id: ${modbus_controller_id}_status_0
    name: Status ${inverter}
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("Standby");
        case 1: return std::string("Normal");
        case 2: return std::string("Discharge");
        case 3: return std::string("Fault");
        case 4: return std::string("Flash");
        case 5: return std::string("PV Charging");
        case 6: return std::string("AC Charging");
        case 7: return std::string("Combined Charging");
        case 8: return std::string("Combined Charging & Bypass");
        case 9: return std::string("PV Charging & Bypass");
        case 10: return std::string("AC Charging & Bypass");
        case 11: return std::string("Bypass");
        case 12: return std::string("PV Charge and Discharge");
        default: return x;
      }

  - platform: modbus_controller
    name: "Inverter Firmware version ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 9
    response_size: 12
    raw_encode: COMMA
    id: ${modbus_controller_id}_version_9
    entity_category: diagnostic
    skip_updates: 5
    disabled_by_default: false

  - platform: modbus_controller
    name: "Inverter Serial Number ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 23
    response_size: 10
    id: ${modbus_controller_id}_serial_23
    entity_category: diagnostic
    skip_updates: 5

  - platform: modbus_controller
    name: "Inverter Date/Time ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 45
    response_size: 12
    raw_encode: COMMA
    lambda: |-
      uint16_t year = data[item->offset] << 8 | data[item->offset+1];
      uint16_t month = data[item->offset+3];
      uint16_t day = data[item->offset+5];
      uint16_t hour = data[item->offset+7];
      uint16_t min = data[item->offset+9];
      return str_snprintf("%04d/%02d/%02d %02d:%02d", 16, year, month, day, hour, min);
    id: ${modbus_controller_id}_date_time_45
    entity_category: diagnostic
    disabled_by_default: false

sensor:
#  - platform: total_daily_energy
#    name: "Grid Energy Today ${inverter}"
#    power_id: grid_power
#    unit_of_measurement: kWh
#    icon: mdi:counter
#    accuracy_decimals: 1
#    #min_save_interval: 1h
#    restore: true
#    filters:
#    - multiply: 0.001
    
#  - platform: total_daily_energy
#    name: "AC Ouput Energy Today"
#    power_id: ac_output_power
#    unit_of_measurement: kWh
#    icon: mdi:counter
#    accuracy_decimals: 2
#    #min_save_interval: 1h
#    restore: true
#    filters:
#      - multiply: 0.001    

  - platform: modbus_controller
    id: ${modbus_controller_id}_solar_voltage
    name: "Solar Voltage ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 1
    register_type: read
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
   
  - platform: modbus_controller
    name: "Solar Power ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 3
    register_type: read
    unit_of_measurement: W
    device_class: power
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    id: ${modbus_controller_id}_solar_current
    name: "Solar Current ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 7
    register_type: read
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.02
    entity_category: diagnostic

  - platform: modbus_controller
    name: "AC Output Power ${inverter}"
    id: ${modbus_controller_id}_ac_output_power
    modbus_controller_id: ${modbus_controller_id}
    address: 9
    register_type: read
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:flash
    value_type: U_DWORD
    accuracy_decimals: 2
    filters:
    - multiply: 0.1
 
  - platform: modbus_controller
    id: ${modbus_controller_id}_battery_voltage
    name: "Battery Voltage ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 17
    register_type: read
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
    - multiply: 0.01

  - platform: modbus_controller
    name: "Battery SoC % ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 18
    register_type: read
    unit_of_measurement: percent
    device_class: battery
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1

  - platform: modbus_controller
    name: "Bus Voltage ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 19
    register_type: read
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    name: "Grid Voltage ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 20
    register_type: read
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    name: "Grid Hz ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 21
    register_type: read
    unit_of_measurement: Hz
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.01

  - platform: modbus_controller
    name: "AC Output Voltage ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 22
    register_type: read
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    entity_category: diagnostic
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    name: "AC Output Hz ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 23
    register_type: read
    unit_of_measurement: Hz
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.01
  
  - platform: modbus_controller
    name: "Inverter Temperature ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 25
    register_type: read
    unit_of_measurement: °C
    device_class: temperature
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:thermometer
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    name: "Load % ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 27
    register_type: read
    unit_of_measurement: percent
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    name: "PV Temperature ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 32
    register_type: read
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    entity_category: diagnostic
    icon: mdi:thermometer
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    name: "AC Output Current ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 34
    register_type: read
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    entity_category: diagnostic

  - platform: modbus_controller
    id: ${modbus_controller_id}_grid_power
    name: "Grid Power ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 36
    register_type: read
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:flash
    value_type: U_DWORD
    accuracy_decimals: 2
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    address: 48
    name: "Solar Energy PV1 Today ${inverter}"
    register_type: read
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1    

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    address: 50
    name: "Solar Energy PV1 Total ${inverter}"
    register_type: read
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1    

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    address: 52
    name: "Solar Energy PV2 Today ${inverter}"
    register_type: read
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1    

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    address: 54
    name: "Solar Energy PV2 Total ${inverter}"
    register_type: read
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1    

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    address: 56
    name: "AC Charge Energy Today ${inverter}"
    register_type: read
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1    

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    address: 58
    name: "AC Charge Energy Total ${inverter}"
    register_type: read
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1    

  - platform: modbus_controller
    name: "Battery Discharge Energy Today ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 60
    register_type: read
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1    

  - platform: modbus_controller
    name: "Grid Current ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 68
    register_type: read
    unit_of_measurement: A
    device_class: current
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:flash
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
  - platform: modbus_controller
    name: "Battery Power ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 77
    register_type: read
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:flash
    value_type: S_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

number:
  - platform: modbus_controller
    name: "Uti Output Start Time ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 3
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 23
    step: 1

  - platform: modbus_controller
    name: "Uti Output End Time Current ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 4
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 23
    step: 1

  - platform: modbus_controller
    name: "Uti Charge Start Time ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 5
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 23
    step: 1

  - platform: modbus_controller
    name: "Uti Charge End Time ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 6
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 23
    step: 1

  - platform: modbus_controller
    name: "Modbus Address ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 30
    register_type: holding
    entity_category: diagnostic
    value_type: U_WORD
    min_value: 1
    max_value: 254
    step: 1

  - platform: modbus_controller
    name: "Max Charge Current ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 34
    value_type: U_WORD
    entity_category: config
    unit_of_measurement: A
    device_class: current
    min_value: 0
    max_value: 130
    step: 1

  - platform: modbus_controller
    name: "Bulk Charge Volt ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 35
    value_type: U_WORD
    entity_category: config
    unit_of_measurement: V
    device_class: voltage
    min_value: 50
    max_value: 58
    step: 0.1
    multiply: 10

  - platform: modbus_controller
    name: "Float Charge Volt ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 36
    value_type: U_WORD
    entity_category: config
    unit_of_measurement: V
    device_class: voltage
    min_value: 50
    max_value: 56
    step: 0.1
    multiply: 10

  - platform: modbus_controller
    name: "Bat Low Volt Switch to Uti ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 37
    value_type: U_WORD
    entity_category: config
    unit_of_measurement: V
    device_class: voltage
    min_value: 44.4
    max_value: 51.4
    step: 0.1
    multiply: 10

  - platform: modbus_controller
    name: "Float Charge Current ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 38
    value_type: U_WORD
    entity_category: config
    unit_of_measurement: A
    device_class: current
    min_value: 0
    max_value: 80
#    step: 0.1
#    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${modbus_controller_id}_modbus_year
    name: "Sys Year ${inverter}"
    address: 45
    value_type: U_WORD
    entity_category: config
    min_value: 2000
    max_value: 2100
    step: 1
    internal: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${modbus_controller_id}_modbus_month
    name: "Sys Month ${inverter}"
    address: 46
    value_type: U_WORD
    entity_category: config
    min_value: 1
    max_value: 12
    step: 1
    internal: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${modbus_controller_id}_modbus_day
    name: "Sys Day ${inverter}"
    address: 47
    value_type: U_WORD
    entity_category: config
    min_value: 1
    max_value: 31
    step: 1
    internal: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${modbus_controller_id}_modbus_hour
    name: "Sys Hour ${inverter}"
    address: 48
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 23
    step: 1
    internal: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${modbus_controller_id}_modbus_minute
    name: "Sys Minute ${inverter}"
    address: 49
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 59
    step: 1
    internal: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${modbus_controller_id}_modbus_second
    name: "Sys Second ${inverter}"
    address: 50
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 59
    step: 1
    internal: true

select:
  - platform: modbus_controller
    name: "On/Off ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 00
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "Standby Off, Output Enable": 0
      "Standby On, Output Enable": 1
      "Standby Off, Output Disable": 0x100
      "Standby On, Output Disable": 0x101

  - platform: modbus_controller
    name: "Charge Source ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 01
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "Pv Priority": 0
      "Pv&Uti": 1
      "Only Pv": 2

  - platform: modbus_controller
    name: "Output Source ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 02
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "Bat Priority": 0
      "Pv Priority": 1
      "Uti Priority": 2
      "Pv&Uti Priority": 3

  - platform: modbus_controller
    name: "PV Input Mode ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 07
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "Independent": 0
      "Parallel": 1

  - platform: modbus_controller
    name: "AC Input Mode ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 08
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "APL,90‐280VAC": 0
      "UPS,170‐280VAC": 1

  - platform: modbus_controller
    name: "Output Volt Type ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 18
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "208 VAC": 0
      "230 VAC": 1
      "240 VAC": 2

  - platform: modbus_controller
    name: "Output Freq Type ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 19
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "50 Hz": 0
      "60 Hz": 1

  - platform: modbus_controller
    name: "Over Load Restart ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 20
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "Yes": 0
      "No": 1
      "Switch to UTI": 2

  - platform: modbus_controller
    name: "Over Temperature Restart ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 21
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "Yes": 0
      "No": 1

  - platform: modbus_controller
    name: "Buzzer on/off enable ${inverter}"
    modbus_controller_id: ${modbus_controller_id}
    address: 22
    value_type: U_WORD
    entity_category: config
    optionsmap:
      "Enable": 0
      "Disable": 1

