esp32:
  board: esp32dev

logger:
  hardware_uart: UART2
  baud_rate: 0

#bluetooth_proxy:

uart:
  tx_pin: GPIO25
  rx_pin: GPIO26
  baud_rate: 38400
  parity: EVEN
  stop_bits: 1
  
sensor:
  - platform: cse7761
    update_interval: 5s
    voltage:
      name: "Voltage"
    current_1:
      name: "Current 1"
    current_2:
      name: "Current 2"
    active_power_1:
      name: "Power 1"
    active_power_2:
      name: "Power 2"

output:
  - platform: gpio
    pin: GPIO27
    id: relay1
  - platform: gpio
    pin: GPIO14
    id: relay2

light:
  - platform: binary
    name: "Switch 1"
    output: relay1
    id: sw1

  - platform: binary
    name: "Switch 2"
    output: relay2
    id: sw2

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    id: button_
    on_press:
      - logger.log: "Button"
      - light.toggle: sw1
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    name: "Switch 1"
    on_press:
      - logger.log: "Switch 1"
      - light.toggle: sw1
  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    name: "Switch 2"
    on_press:
      - logger.log: "Switch 2"
      - light.toggle: sw2
