esp32:
  board: nodemcu-32s

binary_sensor:
  # single main button that also puts device into flash mode when held on boot
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
      ignore_strapping_warning: true
    id: button0
    filters:
      - delayed_on_off: 50ms

switch:
  # template switch to represent the main relay
  # this is synchronised with the RED LED
  - platform: template
    id: main_relay
    name: Relay
    turn_on_action:
      - button.press: main_relay_on
      - light.turn_on: red_led
    turn_off_action:
      - button.press: main_relay_off
      - light.turn_off: red_led
    assumed_state: True
    optimistic: True
    restore_mode: ALWAYS_OFF

  - platform: output
    name: Sensor Power
    id: sensor_power
    output: sensor_power_output
    restore_mode: ALWAYS_ON

output:
  # Ideally, these two relay GPIOs should be interlocked to prevent
  # simultaneous operation. ESPhome currently does not support
  # interlocks at an output: level, or even at a button: level
  # BE CAREFUL!
  - platform: gpio 
    id: main_relay_on_output
    pin:
      number: GPIO19
      inverted: true

  - platform: gpio 
    id: main_relay_off_output
    pin:
      number: GPIO22
      inverted: true

  - platform: ledc 
    id: red_led_output
    pin:
      number: GPIO16
      inverted: true

  - platform: ledc 
    id: green_led_output
    pin:
      number: GPIO13
      inverted: true

  # This is needed to power the external sensor.
  # It receives 3v3 from this pin, which is pulled up on boot.
  - platform: gpio
    pin: GPIO27
    id: sensor_power_output
    
button:
  # See note above about interlocks!
  - platform: output
    id: main_relay_on
    output: main_relay_on_output
    duration: 1000ms
    internal: true

  - platform: output
    id: main_relay_off
    output: main_relay_off_output
    duration: 1000ms
    internal: true

# The middle (blue) LED is used as wifi status indicator.
status_led:
  pin:
    number: GPIO15
    inverted: true
    ignore_strapping_warning: true

light:
  # Leftmost (red) LED that's used to indicate the relay being on/off
  - platform: binary
    id: red_led
    output: red_led_output
    internal: true

  # Rightmost (green) LED
  - platform: binary
    id: green_led
    output: green_led_output
    internal: true

one_wire:
  platform: gpio
  pin: GPIO25

